[package]
name = "ashpd-backend-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
async-trait = "0.1.60"
tokio = { version = "1.0", features = ["io-util", "net", "time", "macros", "rt-multi-thread"] }
byteorder = "1.4.3"
futures-channel = "0.3.25"
futures-util = "0.3.25"
tracing = "0.1"
tracing-subscriber = "0.3.16"
url = "2.3.1"
zbus = "4.2"

[dependencies.ashpd]
path = "../"
features = ["backend", "tracing"]
default-features = false
