mod account;
mod background;
mod camera;
mod dynamic_launcher;
mod email;
mod file_chooser;
mod global_shortcuts;
mod inhibit;
mod input_capture;
mod location;
mod network_monitor;
mod notification;
mod open_uri;
mod print;
mod proxy_resolver;
mod remote_desktop;
mod screencast;
mod screenshot;
mod secret;
mod settings;
mod usb;
mod wallpaper;

pub use account::AccountPage;
pub use background::BackgroundPage;
pub use camera::CameraPage;
pub use dynamic_launcher::DynamicLauncherPage;
pub use email::EmailPage;
pub use file_chooser::FileChooserPage;
pub use global_shortcuts::GlobalShortcutsPage;
pub use inhibit::InhibitPage;
pub use input_capture::InputCapturePage;
pub use location::LocationPage;
pub use network_monitor::NetworkMonitorPage;
pub use notification::NotificationPage;
pub use open_uri::OpenUriPage;
pub use print::PrintPage;
pub use proxy_resolver::ProxyResolverPage;
pub use remote_desktop::RemoteDesktopPage;
pub use screencast::ScreenCastPage;
pub use screenshot::ScreenshotPage;
pub use secret::SecretPage;
pub use settings::SettingsPage;
pub use usb::UsbPage;
pub use wallpaper::WallpaperPage;
