mod account;
mod background;
mod camera;
mod device;
mod email;
mod file_chooser;
mod inhibit;
mod location;
mod network_monitor;
mod notification;
mod open_uri;
mod print;
mod remote_desktop;
mod screencast;
mod screenshot;
mod secret;
mod wallpaper;

pub use account::AccountPage;
pub use background::BackgroundPage;
pub use camera::CameraPage;
pub use device::DevicePage;
pub use email::EmailPage;
pub use file_chooser::FileChooserPage;
pub use inhibit::InhibitPage;
pub use location::LocationPage;
pub use network_monitor::NetworkMonitorPage;
pub use notification::NotificationPage;
pub use open_uri::OpenUriPage;
pub use print::PrintPage;
pub use remote_desktop::RemoteDesktopPage;
pub use screencast::ScreenCastPage;
pub use screenshot::ScreenshotPage;
pub use secret::SecretPage;
pub use wallpaper::WallpaperPage;
