mod account;
mod background;
mod camera;
mod device;
mod email;
mod location;
mod network_monitor;
mod notification;
mod screencast;
mod screenshot;
mod wallpaper;

pub use account::AccountPage;
pub use background::BackgroundPage;
pub use camera::CameraPage;
pub use device::DevicePage;
pub use email::EmailPage;
pub use location::LocationPage;
pub use network_monitor::NetworkMonitorPage;
pub use notification::NotificationPage;
pub use screencast::ScreenCastPage;
pub use screenshot::ScreenshotPage;
pub use wallpaper::WallpaperPage;
